---
storage:
  radarr:
    appdata: 2Gi
  sonarr:
    appdata: 1Gi
  prowlarr:
    appdata: 256Mi
  lidarr: #unused
    appdata: 256Mi
  overseerr:
    appdata: 32Mi
  bazarr:
    appdata: 32Mi
  tdarr:
    config: 4Mi
    logs: 8Mi
    server: 2Gi
  kometa:
    appdata: 1Gi

flaresolverr:
  image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
  port: 8191

overseerr:
  image: ghcr.io/linuxserver/overseerr:1.33.2
  port: 5055

prowlarr:
  image: ghcr.io/linuxserver/prowlarr:1.23.1
  port: 9696

radarr:
  image: ghcr.io/linuxserver/radarr:5.9.1
  port: 7878

sonarr:
  image: ghcr.io/linuxserver/sonarr:4.0.9
  port: 8989

bazarr:
  image: ghcr.io/linuxserver/bazarr:1.4.3
  port: 6767

lidarr:
  image: ghcr.io/linuxserver/lidarr:2.5.3
  port: 8686

tdarr:
  image: ghcr.io/haveagitgat/tdarr:2.24.05
  port: 8265
  resources:
    limits:
      nvidia.com/gpu: 1

kometa:
  image: ghcr.io/linuxserver/kometa:2.0.2
