---
storage:
  radarr:
    appdata: 2Gi
  sonarr:
    appdata: 1Gi
  prowlarr:
    appdata: 256Mi
  lidarr: #unused
    appdata: 256Mi
  overseerr:
    appdata: 32Mi
  bazarr:
    appdata: 32Mi
  tdarr:
    config: 4Mi
    logs: 8Mi
    server: 2Gi
  kometa:
    appdata: 1Gi
  notifiarr:
    appdata: 1Mi

flaresolverr:
  image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
  port: 8191
  resources:
    requests:
      cpu: 512m
      memory: 1Gi

overseerr:
  image: ghcr.io/linuxserver/overseerr:1.33.2
  port: 5055
  resources:
    requests:
      cpu: 10m
      memory: 50Mi

prowlarr:
  image: ghcr.io/linuxserver/prowlarr:1.24.3
  port: 9696
  resources:
    requests:
      cpu: 10m
      memory: 128Mi

radarr:
  image: ghcr.io/linuxserver/radarr:5.11.0
  port: 7878
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

sonarr:
  image: ghcr.io/linuxserver/sonarr:4.0.9
  port: 8989
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

bazarr:
  image: ghcr.io/linuxserver/bazarr:1.4.4
  port: 6767
  resources:
    requests:
      cpu: 10m
      memory: 256Mi

lidarr:
  image: ghcr.io/linuxserver/lidarr:2.5.3
  port: 8686
  resources:
    requests:
      cpu: 10m
      memory: 256Mi

tdarr:
  image: ghcr.io/haveagitgat/tdarr:2.26.01
  port: 8265
  resources:
    requests:
      cpu: 10m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 3Gi
      nvidia.com/gpu: 1

kometa:
  image: ghcr.io/linuxserver/kometa:2.1.0

notifiarr:
  image: ghcr.io/notifiarr/notifiarr:v0.8.2
  port: 5454
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
