---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaresolverr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: flaresolverr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: flaresolverr
                port:
                  number: {{ .Values.flaresolverr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: overseerr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: overseerr
                port:
                  number: {{ .Values.overseerr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: tdarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tdarr
                port:
                  number: {{ .Values.tdarr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: bazarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: bazarr
                port:
                  number: {{ .Values.bazarr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: sonarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sonarr
                port:
                  number: {{ .Values.sonarr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: prowlarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: prowlarr
                port:
                  number: {{ .Values.prowlarr.port }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: radarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: radarr
                port:
                  number: {{ .Values.radarr.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: lidarr.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: lidarr
                port:
                  number: {{ .Values.lidarr.port }}