---
{{- with .Values.kometa }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kometa
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: kometa
    app.kubernetes.io/name: kometa
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: kometa
      app.kubernetes.io/name: kometa
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: kometa
        app.kubernetes.io/name: kometa
    spec:
      containers:
        - name: kometa
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "Australia/Melbourne"
            - name: KOMETA_TIME
              value: "03:00"
            - name: KOMETA_RUN
              value: "False"
          resources:
{{ toYaml .resources | indent 12 }}
          volumeMounts:
            - name: appdata
              mountPath: /config

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: kometa-appdata-pvc
{{- end }}
