---
{{- with .Values.notifiarr }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifiarr
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: notifiarr
    app.kubernetes.io/name: notifiarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: notifiarr
      app.kubernetes.io/name: notifiarr
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: notifiarr
        app.kubernetes.io/name: notifiarr
    spec:
      containers:
        - name: notifiarr
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: MACHINE_ID
              valueFrom:
                secretKeyRef:
                  name: notifiarr-secrets
                  key: machine-id
          resources:
            {{- toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: {{ .port }}
          volumeMounts:
            - name: appdata
              mountPath: /config
            - name: machineid
              mountPath: /etc/machine-id
              subPath: machine-id
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: notifiarr-appdata-pvc
        - name: machineid
          secret:
            secretName: notifiarr-secrets
            items:
              - key: machine-id
                path: machine-id

---
apiVersion: v1
kind: Service
metadata:
  name: notifiarr
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: notifiarr
    app.kubernetes.io/name: notifiarr
  ports:
    - name: notifiarr
      protocol: TCP
      port: {{ .port }}

{{- end }}
