---
{{- with .Values.overseerr }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: overseerr
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: overseerr
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - name: overseerr
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "Australia/Melbourne"
          resources:
{{ toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: {{ .port }}
          volumeMounts:
            - name: appdata
              mountPath: /config
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            httpGet:
              path: /login
              port: {{ .port }}
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            httpGet:
              path: /login
              port: {{ .port }}

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: overseerr-appdata-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
  ports:
    - name: overseerr
      protocol: TCP
      port: {{ .port }}

{{- end }}
