---
{{- with .Values.sonarr }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: GUID
              value: "1001"
            - name: TZ
              value: "Australia/Melbourne"
            - name: DOCKER_MODS
              value: "ghcr.io/themepark-dev/theme.park:sonarr"
            - name: "TP_THEME"
              value: "dracula"
          resources:
{{ toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: {{ .port }}
          volumeMounts:
            - name: appdata
              mountPath: /config
            - name: nfs-media-data
              mountPath: /data
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}
      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: sonarr-appdata-pvc
        - name: nfs-media-data
          nfs:
            path: "/mnt/Slow/Media"
            server: "10.0.3.7"
---

apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  ports:
    - name: sonarr
      protocol: TCP
      port: {{ .port }}

{{- end }}
