---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.sonarr.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.radarr.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.prowlarr.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.lidarr.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.overseerr.appdata }}