---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslacamplayer
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "teslacamplayer.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: teslacamplayer.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: teslacamplayer
                port:
                  number: 5000
