---
{{- with .Values.teslacamplayer }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslacamplayer
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: teslacamplayer
    app.kubernetes.io/name: teslacamplayer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: teslacamplayer
      app.kubernetes.io/name: teslacamplayer
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: teslacamplayer
        app.kubernetes.io/name: teslacamplayer
    spec:
      containers:
        - name: teslacamplayer
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "Australia/Melbourne"
          resources:
{{ toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: 5000
          volumeMounts:
            - name: appdata
              mountPath: /config
            - name: nfs-teslausb
              mountPath: /media
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: 5000
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: 5000

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: teslacamplayer-appdata-pvc
        - name: nfs-teslausb
          nfs:
            path: "/mnt/storage/Backups/TeslaUSB"
            server: "10.0.3.6"

---
apiVersion: v1
kind: Service
metadata:
  name: teslacamplayer
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: teslacamplayer
    app.kubernetes.io/name: teslacamplayer
  ports:
    - name: teslacamplayer-svc
      protocol: TCP
      port: 5000

{{- end }}
