---
changedetection:
  image: ghcr.io/linuxserver/changedetection.io:0.47.03
  port: 5000
  baseUrl: changedetection.k3s.hyde.services
  resources:
    requests:
      cpu: 10m
      memory: 125Mi
  playwright:
    image: browserless/chrome:1.61-chrome-stable
    port: 3000

storage:
  appdata: 128Mi
