---
storage:
  plex:
    appdata: 16Gi
  immich:
  tautulli:
    appdata: 2Gi
  wizarr:
    appdata: 64Mi

immich:
  image: ghcr.io/imagegenius/immich:1.122.2-noml

redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

tautulli:
  image: ghcr.io/linuxserver/tautulli:2.15.0
  resources:
    requests:
      cpu: 10m
      memory: 256Mi

wizarr:
  image: ghcr.io/wizarrrr/wizarr:4.1.1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi

plex:
  image: ghcr.io/linuxserver/plex:1.41.3
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 6
      memory: 4Gi
      nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu.present: "true"
    kubernetes.io/hostname: "discovery"
