apiVersion: v1
kind: ConfigMap
metadata:
  name: excludarr-crontab
  namespace: media-managers
data:
  crontab: |
    0 5 * * * excludarr sonarr exclude -a not-monitored -d -y
    0 5 * * * excludarr radarr exclude -a not-monitored -d -y
    30 5 * * * excludarr sonarr re-add -y
    30 5 * * * excludarr radarr re-add -y
