---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      version: 2.19.5
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: portainer.k3s.hyde.services
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: portainer-tls
          hosts:
            - portainer.k3s.hyde.services
