---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      version: 1.0.52
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    tls:
      force: true
    image:
      tag: '2.21.0'
    ingress:
      enabled: false