creation_rules:
  # Secrets
  - path_regex: .*/*secret.sops.yaml
    encrypted_regex: ^(data|stringData|annotations|)$
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r

    # Config Maps
  - path_regex: .*/*config.sops.yaml
    encrypted_regex: ^(data|stringData|annotations|)$
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r

    # Ingress Hosts
  - path_regex: .*/*ingress.sops.yaml
    encrypted_regex: ^(rules|annotations|)$
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r

    # helm-release
  - path_regex: .*/*helm-release.sops.yaml
    encrypted_regex: ^(values)$
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r

  - path_regex: .*/*basic-auth.sops.yaml
    encrypted_regex: ^(data|stringData|annotations|)$
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r

  - path_regex: .*/*super-sops.yaml
    age: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
