apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: jenkins
      version: 5.7.2
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      image:
        repository: jenkins/jenkins
        tag: 2.479
      sidecars:
        configAutoReload:
          enabled: false
      installPlugins: false
      JCasC:
        defaultConfig: false
      ingress:
        enabled: true
        ingressClassName: external-nginx
        hostName: ci.imagegenius.io
        tls:
          - secretName: wildcard.imagegenius.io
            hosts:
              - ci.imagegenius.io
    agent:
      enabled: false
    persistence:
      size: 2Gi
