apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: jenkins
    namespace: jenkins
    annotations:
        gethomepage.dev/enabled: ENC[AES256_GCM,data:25VhZg==,iv:91Bv4sJDfiLeNhBBNjts8mFqO9pORCbMg/03FIbKNQM=,tag:a3EhN4sxiEZqFyBwV5DHaA==,type:str]
        gethomepage.dev/description: ENC[AES256_GCM,data:shh9SveUtQlZR5nDWepSA3a6VvzkcYUObM5F/IfgTrtZriBv+d5CH1soRE+LneIovnp5JesxpWPl,iv:vBwijXS2ETvVMvBI9kzmP9Ep3Xm3VnX8COccfo+ZEog=,tag:kAmWiYaBvBZs/MUbMQ7c4w==,type:str]
        gethomepage.dev/group: ENC[AES256_GCM,data:KDFYOJiB+iedO5VbdayK1Q==,iv:zkpcpRSEtzdmz2sML8LnAnGnhW2U6ld25ZFTL7x3bQE=,tag:IE2/BrtDICgyg+C512P9TA==,type:str]
        gethomepage.dev/icon: ENC[AES256_GCM,data:FykhquXfrg==,iv:eO0oWM9v2SewAfuELskZQOtuVXn/LIaIHtW+kCUf5zI=,tag:cmWeQzWA8u6uJOWGvT1Y2Q==,type:str]
        gethomepage.dev/name: ENC[AES256_GCM,data:fPsUrQa1Kw==,iv:AolX9NOUbvHI2/FFXKDVNFmq7NGQugklPC2HjsFJzvg=,tag:IcgTcBgCNwDq9ZQxiiOJOg==,type:str]
        gethomepage.dev/namespace: ENC[AES256_GCM,data:kk2/oj8zyw==,iv:KapKGtcyzzXQP1gDtmNJzKrJV2lcY1lkev4fVj4dswU=,tag:/vAenE7SAFx1oNzdK2a9Zg==,type:str]
        gethomepage.dev/app: ENC[AES256_GCM,data:f1+Wk0bvug==,iv:r7DEU2tfEGUxqoqKsBIRmN0aliYXwTbeoStxthww1N0=,tag:shrU9oGDdsbJuq275Aaq3Q==,type:str]
        gethomepage.dev/href: ENC[AES256_GCM,data:rnageqLf8Hrx8ye2LIBlZzZj4WVYOnASvQ==,iv:x4OOcu7cLSI3NHKX5Tb34CEZQBQC7k2OJg+OVVnBSx8=,tag:fOVOXbvHYzvtakb9saSXsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGR2eW5xWjJqUWg5aXN0
            bnZUY25jWnNUeTRDb3Y0VE1Zbk5zK2RPRFFVCnZsYTg1djNaQk9FQmRWN2JHNzE1
            S0NQOEJPQUdIUUJLeUVXbHRyaHB6Y3cKLS0tIEFQN0gwZFQ4b0xNVStVSDhKU0Zo
            Mmg3aDRwZW54a1ZyZytmUFhjUEtDNHMKGZxZ//O4puSOs/H5pwK8eFsLCL69YrJK
            p9xrjiTjXUFC+pzE5YFsXgeOslTFnieufL5sZztaKssKFyMduH0t+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T09:41:45Z"
    mac: ENC[AES256_GCM,data:98QA3ZRaih72ER/65poJWgcebdOK/yRbnzBvORG9PHFXUzffAeId7BaJ5+gtv0bTT+zofXbjnf1lSGWvnWMf0ay+lZisCtn1a4nPSQ7NvRGr+hwm4tMtYF4u8K0vf2NUi8i175eS5B/bjNiYbiQjetVsgPzyDywdLJXF47gcLkM=,iv:aXrRgdpyOPqw0ib+TW5xPguqunZG10Upsg1ZRoyzu2k=,tag:Y7tzyv9xyZDiUfgnKgEr0A==,type:str]
    pgp: []
    encrypted_regex: ^(rules|annotations|)$
    version: 3.9.4
