apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-jenkins
  namespace: jenkins
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: jenkins
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.100.3/32
      ports:
        - protocol: TCP # X86-BUILDER-1
          port: 22
        - protocol: TCP # X86-BUILDER-1a
          port: 2223
        - protocol: TCP # X86-BUILDER-1b
          port: 2224
    - to:
        - ipBlock:
            cidr: 192.168.100.4/32
      ports:
        - protocol: TCP # ARM64-BUILDER-1a
          port: 2223
        - protocol: TCP # ARM64-BUILDER-1b
          port: 2224
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
