---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pterodaactyl
  namespace: pterodaactyl
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./Helm/apps/pterodaactyl
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
