apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: qbittorrent
    namespace: media-downloaders
    annotations:
        gethomepage.dev/enabled: ENC[AES256_GCM,data:25VhZg==,iv:91Bv4sJDfiLeNhBBNjts8mFqO9pORCbMg/03FIbKNQM=,tag:a3EhN4sxiEZqFyBwV5DHaA==,type:str]
        gethomepage.dev/description: ENC[AES256_GCM,data:5lOhJ/FLXXHb8QfnRK0OiLrFpXbludc4e4QZFHjPK/PrLDrHIBxeOZ9OwhA=,iv:lxGRcqeqvBaugp1RZIPFf2cbmEkBpTTs5SEgDTBfxUk=,tag:+eHffxwbpOQ+Pv3FZpN8Gg==,type:str]
        gethomepage.dev/group: ENC[AES256_GCM,data:lrQOWfscg5tn+AbSIrvjI2Y=,iv:warmEha2FRFNAi0ZwoPvmlYL8loqmOt+1j+VMNWTrJM=,tag:qL3K0pgj8KnQPFH0bH/F4Q==,type:str]
        gethomepage.dev/icon: ENC[AES256_GCM,data:y4AlCuFs6l14uxc=,iv:45KK55gMZYXNyBKrnBTghXjg4R040BzHYX9LnAZu+GQ=,tag:heqVQ/MLUG2RFc+oWrzLng==,type:str]
        gethomepage.dev/name: ENC[AES256_GCM,data:KKqyEnR7fL4f+F8=,iv:g8xm5EMtUKbzp5xvelHWBIbqWvmbXEY/p1Rm1hx/4YA=,tag:12zK0r+sWyXM824jzmc7aA==,type:str]
        gethomepage.dev/widget.type: ENC[AES256_GCM,data:Xl+dskRXMAEi01M=,iv:/IuCbXnYJzgfeBLZVkS3hup8gW+Uo88KFJdcHWucrdk=,tag:kMcT57JvteFpO7py47QPQA==,type:str]
        gethomepage.dev/widget.url: ENC[AES256_GCM,data:mmOeEq8A3MZfl1DVY49qMDGMhYdp0sbTgMcBNZfrnlQCpRBGvQ==,iv:MVDBQCSH1wCe/EqIib7Wg9nwEfiP5Iu7CVYK7jv4Sc0=,tag:En81r7zuLv65kRTdnWxMVQ==,type:str]
        gethomepage.dev/widget.username: ENC[AES256_GCM,data:e27lmeY=,iv:AmmbGUf75DLTQEkmUZN/+myabHHNeG7nEQiaEeg+ULA=,tag:vLB1tDVlS1mgIS1yhinMYg==,type:str]
        gethomepage.dev/widget.password: ENC[AES256_GCM,data:FyCRyE+vHc6LSg==,iv:zIySpzuRdPqDzVlC8NMJIVm8/YIMzwisz0D11Ii0pq4=,tag:M2ti7UvdpJ36TYhE1Qqfzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGR2eW5xWjJqUWg5aXN0
            bnZUY25jWnNUeTRDb3Y0VE1Zbk5zK2RPRFFVCnZsYTg1djNaQk9FQmRWN2JHNzE1
            S0NQOEJPQUdIUUJLeUVXbHRyaHB6Y3cKLS0tIEFQN0gwZFQ4b0xNVStVSDhKU0Zo
            Mmg3aDRwZW54a1ZyZytmUFhjUEtDNHMKGZxZ//O4puSOs/H5pwK8eFsLCL69YrJK
            p9xrjiTjXUFC+pzE5YFsXgeOslTFnieufL5sZztaKssKFyMduH0t+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-01T04:27:56Z"
    mac: ENC[AES256_GCM,data:mU5C0fWoDUid/mMMjUNOgG+YJdJSSlLPXzIlGLiW7HhuNOjUvWOfIR48V7sog7LgUiAAZZw7jLUPDmnZtA5JKzYCRd+EZgbbEBzuX5/jaZY/Zgy98WcWz+GDRiQKt2qx7x7DukJndV+1vWp2qCpYbarEaKuy9IaoV1T0alYBSGQ=,iv:2HS580R/rLNsbONVz+n/KUnBW1tEZ4LWwI/OIm5f8Jc=,tag:icYLTYyrnD4mA6/O0E9lkg==,type:str]
    pgp: []
    encrypted_regex: ^(rules|annotations|)$
    version: 3.9.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: sabnzbd
    namespace: media-downloaders
    annotations:
        gethomepage.dev/enabled: ENC[AES256_GCM,data:25VhZg==,iv:91Bv4sJDfiLeNhBBNjts8mFqO9pORCbMg/03FIbKNQM=,tag:a3EhN4sxiEZqFyBwV5DHaA==,type:str]
        gethomepage.dev/description: ENC[AES256_GCM,data:2cgJmXR9kj35nKUZl7SfxtbSxn/AO+LTvFz3,iv:AH7VA2flYtvPiG/OAZHS7FnI4gY+IvnVAN/SRxcVm8s=,tag:LyN/OhuUEBivfDlWfk8OuA==,type:str]
        gethomepage.dev/group: ENC[AES256_GCM,data:lrQOWfscg5tn+AbSIrvjI2Y=,iv:warmEha2FRFNAi0ZwoPvmlYL8loqmOt+1j+VMNWTrJM=,tag:qL3K0pgj8KnQPFH0bH/F4Q==,type:str]
        gethomepage.dev/icon: ENC[AES256_GCM,data:icmarjj6/A==,iv:FJ6Qyv1POW1j+Li3xFvaPlRET+dl0DmMnwcDeO/KWJY=,tag:Daf5WRZt0b50hRO5iDSF7A==,type:str]
        gethomepage.dev/name: ENC[AES256_GCM,data:yjQUF1kU4g==,iv:JruluAYixVL//3WmUC9l9hWtOcKqT651HcU5Sc0Y8J0=,tag:DJU6ZZ7GORLXEanrg9i/7A==,type:str]
        gethomepage.dev/widget.type: ENC[AES256_GCM,data:faaUoM+DtA==,iv:34b5EpRy61m8HiHUB1ywPD5E4zzcTQODG5VGGyTKLc0=,tag:c7XArZb2yvs9nqDELtFS/Q==,type:str]
        gethomepage.dev/widget.url: ENC[AES256_GCM,data:1lZ7pyqzT+Bt0tP3Sa4/2YCKU62RR/wyHSiazj5U6t0R,iv:QYeElgdb7w1CsHk3u0ZeUKdz8OU8GIlpWhg0cToFsLc=,tag:UHKPs3RzPn3hs5McPAm/dg==,type:str]
        gethomepage.dev/widget.key: ENC[AES256_GCM,data:8ZUFFGg4yfcwapx455OGsCsXMK5IzI9F5ZURCnKUpnk=,iv:61x5wiU8ctJG6aXbU+QqFWv2AbIaKwCXsolpx4czsXo=,tag:9C4eyoHpdanxDQJkcsBkyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGR2eW5xWjJqUWg5aXN0
            bnZUY25jWnNUeTRDb3Y0VE1Zbk5zK2RPRFFVCnZsYTg1djNaQk9FQmRWN2JHNzE1
            S0NQOEJPQUdIUUJLeUVXbHRyaHB6Y3cKLS0tIEFQN0gwZFQ4b0xNVStVSDhKU0Zo
            Mmg3aDRwZW54a1ZyZytmUFhjUEtDNHMKGZxZ//O4puSOs/H5pwK8eFsLCL69YrJK
            p9xrjiTjXUFC+pzE5YFsXgeOslTFnieufL5sZztaKssKFyMduH0t+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-01T04:27:56Z"
    mac: ENC[AES256_GCM,data:mU5C0fWoDUid/mMMjUNOgG+YJdJSSlLPXzIlGLiW7HhuNOjUvWOfIR48V7sog7LgUiAAZZw7jLUPDmnZtA5JKzYCRd+EZgbbEBzuX5/jaZY/Zgy98WcWz+GDRiQKt2qx7x7DukJndV+1vWp2qCpYbarEaKuy9IaoV1T0alYBSGQ=,iv:2HS580R/rLNsbONVz+n/KUnBW1tEZ4LWwI/OIm5f8Jc=,tag:icYLTYyrnD4mA6/O0E9lkg==,type:str]
    pgp: []
    encrypted_regex: ^(rules|annotations|)$
    version: 3.9.0
