apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    installCRDs: true
    controller:
      ingressClassResource:
        name: external-nginx
        controllerValue: "k8s.io/ingress-external"
      service:
        loadBalancerIP: 207.211.157.130
        externalTrafficPolicy: Local
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
