---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.plex.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pg-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.immich.postgres }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.tautulli.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarr-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.wizarr.appdata }}
