---
{{- with .Values.tautulli }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/name: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: tautulli
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: tautulli
        app.kubernetes.io/name: tautulli
    spec:
      containers:
        - name: tautulli
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: GUID
              value: "1001"
            - name: TZ
              value: "Australia/Melbourne"
          resources:
{{ toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: 8181
          volumeMounts:
            - name: appdata
              mountPath: /config
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: 8181
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: 8181

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: tautulli-appdata-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/name: tautulli
  ports:
    - name: tautulli
      protocol: TCP
      port: 8181

{{- end }}
