---
{{- with .Values.wizarr }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: wizarr
    app.kubernetes.io/name: wizarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: wizarr
      app.kubernetes.io/name: wizarr
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: wizarr
        app.kubernetes.io/name: wizarr
    spec:
      containers:
        - name: wizarr
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: APP_URL
              value: "https://wizarr.hyde.services"
            - name: TZ
              value: "Australia/Melbourne"
          resources:
{{ toYaml .resources | indent 12 }}
          ports:
            - name: web
              containerPort: 5690
          volumeMounts:
            - name: appdata
              mountPath: /data/database
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: 5690
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: 5690

      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: wizarr-appdata-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wizarr
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: wizarr
    app.kubernetes.io/name: wizarr
  ports:
    - name: wizarr
      protocol: TCP
      port: 5690

{{- end }}
