---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: gpu-operator
      version: v24.9.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  values:
    toolkit:
      env:
        - name: CONTAINERD_CONFIG
          value: "/etc/containerd/config.toml.tmpl" # don't know if this should reference the rancher config, but still works so whatever
        - name: CONTAINERD_SOCKET
          value: "/run/k3s/containerd/containerd.sock"
        - name: CONTAINERD_RUNTIME_CLASS
          value: "nvidia"
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"

    devicePlugin:
      config:
        name: time-slicing-config
        default: any
