apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-config
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:8jp8ELMOKasyL38vTgU=,iv:1OEUbQEGyvfYacprl3B+defr7RBlDMJTgbrBaTdcAZ0=,tag:H4O6NVMlmH8wXebnm4nkLA==,type:str]
    settings.yaml: ENC[AES256_GCM,data:bqDshQYj79XMzBLVAA+UiJ8=,iv:Q7tUU7O3+y8GHkS67ecFxZleSdRO6G4k4hRcQp4qIO0=,tag:ZbncJKfLAzSddkiWhf9NRQ==,type:str]
    bookmarks.yaml: ENC[AES256_GCM,data:A6BYqxuL+cP9w8ebmM/AetbFI9abhBWCP8PCpF+p01ZI3OzLOuTH8sNRk2gcxQhPnSDZjX7gPKilNDlDoo3OJLV29BP5PleaIAs=,iv:CNfA/pevhX15p2JrUZIo7G34w8q4Eh4/Is3R0/wIAio=,tag:zFf9jAK14qbFqVdCO5IQWw==,type:str]
    services.yaml: ENC[AES256_GCM,data:+v9gVr7xrnPCupZjss9yz3TbcIxZoBjWKDploxN62SNiOXCfwCg4z4F8YWg6m0zoRC3sZRSsvHaSVIQ9QnCgS2UZ6iLEaIDjahtXkIZQXKekTpc4,iv:I4oM/f3Ybj2SdAnIjdXCfmgMsbw9Gw+Dicd5dTU9P6s=,tag:5mUHEnp3Ja+upsYglOL/tg==,type:str]
    widgets.yaml: ENC[AES256_GCM,data:iZGGAqHqSxL4IHVAe7yXn535odh5WdL1mq3ZIDOAXvfUdy+/zJTNfudvG4kZV/TVmK83aXon44H4r7JHrASFA6pNu8tvJsJvOaDZkKks2qQz3qn8KZsCJj+2Uc/LSUkw5JuDp1zg80ZTJ/F3b9Ifgx8AdViVFtBaKVmNGEB/x3MKGqJmwOSrb6L4MU90PKiMONko3PKA7quTMfSGMZgjl73R2cy0C2H+YE8bY8na0zsrWqfqYj27Y6PX2pVofR2ZqxmOs3/gCX5btvBAjPqBrsmo1Iwluw4+BkXK5Y5C0U1vyLjr0rF0uZJ+u3AqnLgcT45pHnP1awYPkHOdp+tT6f0HuSPVnO3MzjN1K63103bbZKig3yqfPeHxlzhol7xO51yVVW+TrWbFXoLysn94nWFJhcdvRxZqyllcelj50snzSHQVrOgclXlj7McSX44f7aztjgTJjayKxuVaFZAAH63Pb5TDurlS/Zenitcd3w1BbSmhdFct,iv:3mrW1Rnv/2pLr6mezZ8DYEtpJOPXhc1Zl1codtpBi7c=,tag:6uhw8B7alKuXE48Pfaw8Hg==,type:str]
    docker.yaml: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS29objhNMTU1MnoyRXJ4
            OHkzbFV6MVFLdExHbXNTVlRmVHRORjVVSFM4ClIzaDc2aURVVFI5cWZzaXB2U2Vz
            T1l4eEFoOXFHd1pVa0JIeWFvcE9LUlUKLS0tIFhTL05LMklkSk5HRmFyTjMvT2Vq
            OXZnN2JwWlR1bVZHalZCUVlpWHAzMjQKF6x/CdpISWSwyWKiEKTKd2fCo6jSGS2b
            KgObfc3oo4KxFRqK2OO5rWV87bbpnStNcN8TulIcSE1faLvMTyYXTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T09:48:30Z"
    mac: ENC[AES256_GCM,data:G3v+RLnXF7/Z+RnJX0FpUryxjT/SV3V19IJor6GfxoknzMT+e0HlP4hxJkv+qY7ujt8yh1aOmqRxNhFc6LjYyCiUlAQmN/zSeoyVzFlLF2d/r98nyYNEoauqM9hvHhu6PaSZhtTdN0SqpoPs3+QhMFcUo0UO1rCx9pYDrDn6dzM=,iv:R/9m+K4/fBjF27GuXnm4kD2M7ABfbt526/7T6GrCe8U=,tag:yYrTQrnpjdNr7wn9rTK1+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.0
