---
{{- with .Values.uptime-kuma }}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: uptime-kuma
    namespace: {{ $.Release.Namespace }}
    labels:
        app.kubernetes.io/instance: uptime-kuma
        app.kubernetes.io/name: uptime-kuma
spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
        matchLabels:
            app.kubernetes.io/instance: uptime-kuma
            app.kubernetes.io/name: uptime-kuma
    template:
        metadata:
            annotations:
                backup.velero.io/backup-volumes: appdata
            labels:
                app.kubernetes.io/instance: uptime-kuma
                app.kubernetes.io/name: uptime-kuma
        spec:
            containers:
                - name: uptime-kuma
                  image: {{ .image }}
                  imagePullPolicy: IfNotPresent
{{- if .resources }}
                  resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
                  ports:
                      - name: web
                        containerPort: {{ .port }}
                  volumeMounts:
                      - name: appdata
                        mountPath: /app/data
                  livenessProbe:
                      failureThreshold: 5
                      tcpSocket:
                          port: {{ .port }}
                  startupProbe:
                      failureThreshold: 5
                      initialDelaySeconds: 10
                      tcpSocket:
                          port: {{ .port }}

            restartPolicy: Always
            volumes:
                - name: appdata
                  persistentVolumeClaim:
                      claimName: uptime-kuma-appdata-pvc

---

apiVersion: v1
kind: Service
metadata:
    name: uptime-kuma
    namespace: {{ $.Release.Namespace }}
spec:
    selector:
        app.kubernetes.io/instance: uptime-kuma
        app.kubernetes.io/name: uptime-kuma
    ports:
        - name: uptime-kuma
          protocol: TCP
          port: {{ .port }}

{{- end }}
