---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: uptime-kuma
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Uptime Monitor
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: uptime-kuma
        gethomepage.dev/name: Uptime Kuma
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - "*.k3s.hyde.services"
          secretName: ingress
    rules:
        - host: uptime-kuma.k3s.hyde.services
          http:
              paths:
                  - pathType: Prefix
                    path: "/"
                    backend:
                        service:
                            name: uptime-kuma
                            port:
                                number: {{ .Values.uptime-kuma.port }}