---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - "uptime-kuma.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: uptime-kuma.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: uptime-kuma
                port:
                  number: {{ .Values.uptimekuma.port }}
