---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.uptime-kuma.appdata }}
