---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      version: 1.0.57
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  values:
    image:
      repository: portainer/portainer-ee
      tag: 2.23.0
    service:
      type: ClusterIP
    tls:
      force: true
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - host: portainer.k3s.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - portainer.k3s.hyde.services
          secretName: wildcard.hyde.services
    persistence:
      size: 128Mi
