---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.sops.yaml
  - namespace.yaml
patches:
  - path: velero-annotation-patch.yaml
    target:
      kind: Deployment
      name: portainer
      namespace: portainer
