---
storage:
  loki:
    appdata: 128Mi
    logs: 2Gi
  promtail:
    position: 256Mi
  influxdb:
    appdata: 2Gi

kube-prometheus-stack:
  grafana:
    defaultDashboardsTimezone: Australia/Melbourne
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hosts:
        - grafana.k3s.hyde.services
      paths:
        - /
      tls:
        - secretName: wildcard.hyde.services
          hosts:
            - grafana.k3s.hyde.services
  prometheus:
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hosts:
        - prometheus.k3s.hyde.services
      paths:
        - /
      tls:
        - secretName: wildcard.hyde.services
          hosts:
            - prometheus.k3s.hyde.services

loki:
  image: grafana/loki:3.2.1
  port: 3100
  resources:
    requests:
      cpu: 125m
      memory: 50Mi
    limits:
      memory: 2Gi

promtail:
  image: grafana/promtail:3.2.1
  resources:
    requests:
      cpu: 50m
      memory: 250Mi

influxdb:
  image: influxdb:2.7.10
  port: 8086
