---
storage:
  grafana:
    appdata: 128Mi
  prometheus:
    appdata: 4Gi
  loki:
    appdata: 128Mi
    logs: 2Gi
  promtail:
    position: 256Mi
  influxdb:
    appdata: 2Gi

prometheus:
  image: quay.io/prometheus/prometheus:v2.54.1
  port: 9090

nodeExporter:
  image: prom/node-exporter:v1.8.2
  port: 9100
  tolerations:
    - key: CriticalAddonsOnly
      effect: NoSchedule

grafana:
  image: grafana/grafana:11.2.0
  port: 3000
  resources:
    requests:
      cpu: 10m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 1Gi

cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.45.0-containerd-cri
  port: 8080
  resources:
    requests:
      memory: 50Mi
      cpu: 10m
    limits:
      memory: 500Mi
      cpu: 100m

loki:
  image: grafana/loki:3.2.0
  port: 3100
  resources:
    requests:
      cpu: 125m
      memory: 50Mi
    limits:
      memory: 2Gi

promtail:
  image: grafana/promtail:3.2.0
  resources:
    requests:
      cpu: 50m
      memory: 250Mi

influxdb:
  image: influxdb:2.7.10
  port: 8086

kubestatemetrics:
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
