apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: ingress-nginx
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:aCtn0A==,iv:IBr9Ar3MBOdiSisvwbNolrPHqeaUGV3Ifk7a4fXn0Kk=,tag:z7VhuWy/RAZgu/uNk8Iylw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:ZwY9Rw==,iv:scp3v/M8ks0S96wdNbupYcQPRQ38fqyLhiOkbf8icKA=,tag:uhiSKvL9ENdhA94rKZnfLw==,type:str]
type: Opaque
data:
    auth: ENC[AES256_GCM,data:+4weGEAEXsh1MLZa0xt8E6Urvgw=,iv:SbBDVOZ/nZGLcfanUmojrnrLPgkGOPtaNXzbhDUQsSk=,tag:zLmyci7JiH+PUFP9j/KoFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU242SVBwYU54M01iNXky
            U2pRaURvaU9ycFJIeW01L25sNXg1c2VUL0RnCmRyTzh4MTVuUUlaVTQ2YnZvbE1o
            ZEJ1OVBIMXpqNHQ1T0Fnb3JTNDBDb1UKLS0tIDNHZ1psRkNsbU5GV3hTbFBLQ2JI
            WWg2ZUVSbmUzaitsejlGbk1CeE1CR2sKwEiFKkF3nQTHN+XS9ewXx6I3iY8+ZU+D
            6yjPo2ixCmmD9XUKTeoW3gPnHxVJXL7PIRJ68xm4rN/ES2/He79H2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T11:55:35Z"
    mac: ENC[AES256_GCM,data:D4qFT+hx+/bZMkDu52iKhUSmOf9q0fFP4gV5DmOJDW6asHXWLEWA34tC+SpwSvVLRCa1as2gPdQS5O88KP7YS3DDDrhj2WB02sgpEiG7TaC1h0vo3w5OolF+WI5XdbvmLAS6MKNytkasgSCqrHbvzRQYG0p9QgFrwOGuHyXFpJQ=,iv:fMJttGWmReNNBgQ7eEsOr/HNH9H4wCsTfvKfPb52+cM=,tag:lAmNDCMiyzbptP9k+9if8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.0
