{{- range .Values.instances }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .domain | replace "." "-" }}-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-hide-headers: "Referrer-Policy, X-Content-Type-Options, X-Frame-Options, X-XSS-Protection"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - "{{ .domain }}"
      secretName: {{ .tlssecret }}
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .domain | replace "." "-" }}-svc
                port:
                  number: {{ $.Values.nextcloud.port }}
{{- end }}
