---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: pgadmin
    namespace: {{ $.Release.Namespace }}
    annotations:
        kubernetes.io/ingress.class: "nginx"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: PostgreSQL admin pannel
        gethomepage.dev/group: Databases
        gethomepage.dev/icon: pgadmin
        gethomepage.dev/name: pgAdmin
spec:
    tls:
        -   hosts:
                - "*.k3s.hyde.services"
            secretName: ingress
    rules:
        -   host: pgadmin.k3s.hyde.services
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: pgadmin
                                port:
                                    number: {{ .Values.pgadmin.port }}
