---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: pgadmin
    namespace: {{ $.Release.Namespace }}
spec:
    tls:
        -   hosts:
                - "*.k3s.hyde.services"
            secretName: ingress
    rules:
        -   host: pgadmin.k3s.hyde.services
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: pgadmin
                                port:
                                    number: {{ .Values.pgadmin.port }}
