---
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install unifi-protect-backup
maintainers:
    - email: alexanderhyde@icloud.com
      name: Alex hyde
name: unifi-protect-backup
type: application
version: 1.0.0
