apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: minio
      version: 5.2.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-09-13T20-26-02Z
    mode: standalone
    existingSecret: minio-secrets
    persistence:
      size: 1Gi
    ingress:
      enabled: true
      ingressClassName: external-nginx
      path: /
      hosts:
        - s3.imagegenius.io
      tls:
        - secretName: wildcard.imagegenius.io
          hosts:
            - s3.imagegenius.io
    resources:
      requests:
        memory: 512Mi