---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - portainer
  - media-managers
  - media-servers
  - monitoring
  - uptime-kuma
  - unifi-protect-backup