---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cert-manager
  - changedetection
  - homepage
  - jenkins
  - mailserver
  - database
  - media-downloaders
  - media-managers
  - media-servers
  - minio
  - monitoring
  - nextcloud
  - paperless-ngx
  - unifi-protect-backup
  - uptime-kuma
  - wordpress