---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cert-manager
# - changedetection # to fix
  - database
  - homepage
  - jenkins
  - knick-knacks
  - mailserver
  - media-downloaders
  - media-managers
  - media-servers
  - minio
  - monitoring
  - nextcloud
  - paperless-ngx
  - uptime-kuma
  - wordpress
