---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: unifi-protect-backup-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: {{ .Values.storage.size }}
