---
{{- with .Values.grafana }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      restartPolicy: Always
      containers:
        - name: grafana
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .port }}
              name: http-grafana
              protocol: TCP
          resources:
{{ toYaml .resources | indent 12 }}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: appdata
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: grafana-appdata-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: {{ .port }}
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: TCP
      targetPort: http-grafana
      name: grafana
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  {{- with .nodePort }}
  type: NodePort
  {{- end }}

{{- end }}
