---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: grafana
    namespace: {{ $.Release.Namespace }}
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - "*.k3s.hyde.services"
            secretName: wildcard.hyde.services
    rules:
        -   host: grafana.k3s.hyde.services
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: grafana
                                port:
                                    number: {{ .Values.grafana.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: prometheus
    namespace: {{ $.Release.Namespace }}
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - "*.k3s.hyde.services"
            secretName: wildcard.hyde.services
    rules:
        -   host: prometheus.k3s.hyde.services
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: prometheus
                                port:
                                    number: {{ .Values.prometheus.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: loki
    namespace: {{ $.Release.Namespace }}
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - "*.k3s.hyde.services"
            secretName: wildcard.hyde.services
    rules:
        -   host: loki.k3s.hyde.services
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: loki
                                port:
                                    number: {{ .Values.loki.port }}
---
