{{- with .Values.grafana }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-appdata-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 128Mi

{{- end }}

{{- with .Values.prometheus }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-appdata-pvc
spec:
    storageClassName: longhorn
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 4Gi

{{- end }}

{{- with .Values.loki }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki-appdata-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 128Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki-logs-pvc
spec:
    storageClassName: longhorn
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi

{{- end }}

{{- with .Values.promtail }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: promtail-position-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

{{- end }}
