---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.grafana.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-appdata-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.prometheus.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-appdata-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.loki.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-logs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.loki.logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-position-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.promtail.position }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-appdata-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.influxdb.appdata }}
