apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ENC[AES256_GCM,data:53a3czNJOw7g7vReXSH+,iv:xOYLbPKk78TKijq6HxMO5M8P+2V1U0vTBmF+y1ZRCD0=,tag:ySbigpKL8dJJGKQ6FoQI5w==,type:str]
    namespace: wordpress
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: wordpress
            version: 23.1.13
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: ENC[AES256_GCM,data:BYyNC5JPXA==,iv:e7f6xnwfloaqtsA0JjjQeX4gSAmR/JBiwp/olGlVGyk=,tag:5Y1l66YSztLq4kPFYpSzxw==,type:str]
                namespace: flux-system
    values:
        image:
            repository: bitnami/wordpress
            tag: 6.6.2-debian-12-r2
        mariadb:
            enabled: false
        wordpressConfigureCache: true
        htaccessPersistenceEnabled: true
        ingress:
            enabled: true
            ingressClassName: external-nginx
            hostname: ENC[AES256_GCM,data:xV52gYamgI01QVQFxEyF,iv:GbYHl60GOhTjGd25DcyihAOYJk8ibRqFNUgYJ6ooFus=,tag:cSAnVT3KqcIQd0+jTXsA9A==,type:str]
            tls: true
            extraTls:
                - hosts:
                    - ENC[AES256_GCM,data:AT1jjieU5NBBkbboEcIa,iv:IChClpqvyJB82rZvZK2RpAH9CND0NkQxDZ6NmNWMP4s=,tag:/Jin0T4ZPy09fGLvNF+ekA==,type:str]
                  secretName: ENC[AES256_GCM,data:nFL5aUJbQUZL99KKCVXAWQZavzwCy8mP,iv:9gtMaGNxhv/s8VxT2Bpvy4DVCoF3GDkBlX1IQo+L0ic=,tag:ZQMSbwBUXZx9HVY1ToIPxQ==,type:str]
        memcached:
            enabled: false
        externalCache:
            host: memcached.wordpress.svc.cluster.local
            port: 11211
        persistence:
            size: 1Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZkVpbllXNmVLZU1nOXBK
            ZlY5aXJLcDZNNnF4c3BDMk9oVEE3L3ZHSTBFClBxbUtqZDYwVjhua3d6clRQMUQr
            N1loMEtvZDY2N2V5UVJmaHlSVnBNdncKLS0tIGl6a1lScG9OL0JYM3NqNHltdGJN
            RXBac0ZGUitFc3pubm5ONU9QTHhJRXMK6QgQz+/ZvgGlbOEInTwBfusxEXxLi+iX
            P3CWEbPVYmX9OPEOQvId1yho5CFkV4ac3nc+uaqYXLNqfhJ63MVe2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T10:53:16Z"
    mac: ENC[AES256_GCM,data:7LH7MqaX2W4Y9yqG/aI1J6eQHNn2lIIL09wn5lyJP1OZUhNLeq5eH90vzBCzzL36EgoNPFpLwat6Sg4lkJGcJV9JdsUWtZmoDp88+o3omeW7UQ2w9LJlxNm7mgi9KruHOr5LY/w3xs5f9nMZEwmtbHbL8J1xju9SmBK/jc4dogw=,iv:b6+z4Ne1fOW41BCTEdpHVMq1JFI8LKouBDZGCe34VJw=,tag:0uOGSlGi/eduYXs0lS/QBw==,type:str]
    pgp: []
    encrypted_regex: ^(name|hostname|extraTls|)$
    version: 3.9.0
