apiVersion: v1
data:
    mariadb-password: ENC[AES256_GCM,data:dsfLcZyhU0UzCFDjtot/1x+oTl/LEpKh,iv:wp/eFs3k0oJMg9Sa0n569s8TY6fW+LDE+Rr5gGl9s7o=,tag:2cgAB6K8lecEmO1fQDjPKg==,type:str]
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:0+wJxNLaiBYYCuItdYoSEW9JCP/w0Xg=,iv:y2LaxxBcmvNlr4FwEWSOvhJDCcKeK9EIKCoE/1ihdEU=,tag:1Tb3KmMY4beM5Rkw925kpg==,type:str]
    namespace: wordpress
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRDdzWWlhZWxUdlFvdnI1
            QWh6cWswQ1RYN2xlYmJVNXl5MDZFdmtXWGdFCnhIY3FDYVJ2eG41WmloSzB5ejEw
            QVVOUzJENUdGcnBGOHdrazNVd1IzbjAKLS0tIDUybGd3SGZqNzZBeDFIekxFWG9C
            NG9qUFJNNDZoRitKdUp6RW1RWEtENTAK/mIIFvgQkDZLU39QLRuax7DKectxcxeI
            OCe8z0GgvwihlTKgpSSjztGAVgrwvfefYsv4ttLSPeYbNG9EhS1adQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T11:04:12Z"
    mac: ENC[AES256_GCM,data:EJa+wJ974e/BzGmODT7RDIFSAmV6am0TkRKPcA8zn3o4awsFOJ5CC2DjtoPmJ8bIUTQdiMn7lrLZa/rj+lLB5hsNGxGNHbjoo3eAyGhxgnOUQyHNex/dqSQy9c4tAt91Y9x5tzs08antzw5iv4GpAgi+dfmiuGHBpvdvsbyhRkQ=,iv:XPFr9Kb9aMfzE6GGTsd3Skc1yqK7TMlVEd6vgzZuK2o=,tag:+iFDRdNDns//qW/4ade0Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|name|)$
    version: 3.9.0
