---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: longhorn-system
    namespace: longhorn-system
spec:
    interval: 5m
    install:
        createNamespace: true
    chart:
        spec:
            chart: longhorn
            version: 1.7.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: longhorn-system
                namespace: flux-system
    values:
        enablePSP: false
        ingress:
            enabled: true
            host: longhorn.k3s.hyde.services
            ingressClassName: nginx
            tls: true
            tlsSecret: wildcard.hyde.services
            annotations:
                nginx.ingress.kubernetes.io/auth-type: basic
                nginx.ingress.kubernetes.io/auth-secret: basic-auth
                nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        longhornManager:
            tolerations: 
              - key: "CriticalAddonsOnly"
                operator: "Equal"
                effect: "NoSchedule"
                value:
        longhornDriver:
            tolerations: 
              - key: "CriticalAddonsOnly"
                operator: "Equal"
                effect: "NoSchedule"
                value:
        defaultSettings:
            taintToleration: "CriticalAddonsOnly:NoSchedule"
