---
{{- with .Values.changedetection }}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: changedetection
    namespace: {{ $.Release.Namespace }}
    labels:
        app.kubernetes.io/instance: changedetection
        app.kubernetes.io/name: changedetection
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: changedetection
            app.kubernetes.io/name: changedetection
    template:
        metadata:
            annotations:
              backup.velero.io/backup-volumes: appdata
            labels:
                app.kubernetes.io/instance: changedetection
                app.kubernetes.io/name: changedetection
        spec:
            containers:
                - name: playwright-chrome
                  image: {{ .playwright.image }}
                  imagePullPolicy: IfNotPresent
                  ports:
                      - name: playwright-chrome
                        containerPort: {{ .playwright.port }}
                  env:
                      - name: SCREEN_WIDTH
                        value: "1920"
                      - name: SCREEN_HEIGHT
                        value: "1024"
                      - name: SCREEN_DEPTH
                        value: "16"
                      - name: MAX_CONCURRENT_CHROME_PROCESSES
                        value: "10"
                      - name: STATS_REFRESH_SECONDS
                        value: "120"
                  resources: 
                      limits:
                          memory: 2Gi
                  volumeMounts:
                      - name: shm-empty-playwright
                        mountPath: /dev/shm
                  livenessProbe:
                      failureThreshold: 10
                      initialDelaySeconds: 30
                      tcpSocket:
                          port: {{ .playwright.port }}
                      timeoutSeconds: 2
                  startupProbe:
                      failureThreshold: 20
                      timeoutSeconds: 2
                      tcpSocket:
                          port: {{ .playwright.port }}
                - name: changedetection
                  image: {{ .image }}
                  imagePullPolicy: IfNotPresent
{{- if .resources }}
                  resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
                  ports:
                      - name: web
                        containerPort: {{ .port }}
                  volumeMounts:
                      - name: data-config
                        mountPath: /config
                  env:
                      - name: PUID
                        value: "1000"
                      - name: PGID
                        value: "1000"
                      - name: LC_ALL
                        value: "en_US.UTF-8"
                      - name: BASE_URL
                        value: "{{ .baseUrl }}"
                      - name: PLAYWRIGHT_DRIVER_URL
                        value: "ws://localhost:{{ .playwright.port }}/?stealth=1&--disable-web-security=true"
                  livenessProbe:
                      failureThreshold: 10
                      initialDelaySeconds: 30
                      tcpSocket:
                          port: {{ .port }}
                      timeoutSeconds: 2
                  startupProbe:
                      failureThreshold: 20
                      timeoutSeconds: 2
                      tcpSocket:
                          port: {{ .port }}

            restartPolicy: Always
            volumes:
                - name: data-config
                  persistentVolumeClaim:
                      claimName: changedetection-appdata-pvc
                - name: shm-empty-playwright
                  emptyDir:
                      medium: Memory

---

apiVersion: v1
kind: Service
metadata:
    name: changedetection
    namespace: {{ $.Release.Namespace }}
spec:
    selector:
        app.kubernetes.io/instance: changedetection
        app.kubernetes.io/name: changedetection
    ports:
        - name: changedetection
          protocol: TCP
          port: {{ .port }}

{{- end }}
