---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: changedetection
    namespace: {{ $.Release.Namespace }}
spec:
    ingressClassName: internal-nginx
    tls:
        - hosts:
              - "*.k8s.hyde.services"
          secretName: wildcard.hyde.services
    rules:
        - host: changedetection.k8s.hyde.services
          http:
              paths:
                  - pathType: Prefix
                    path: "/"
                    backend:
                        service:
                            name: changedetection
                            port:
                                number: {{ .Values.changedetection.port }}
