---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: changedetection-appdata-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: {{ .Values.storage.appdata }}
