apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-custom-css
  namespace: authentik
data:
  custom.css: |
    /*** global ***/
    :root {
    	--ak-accent: #3a244a;
    	--pf-global--primary-color--100: #70468e;
    	--pf-global--primary-color--200: #55356c;
    	--pf-global--primary-color--400: var(--ak-accent);
      }

    .pf-c-login__main,
    .pf-c-login__main::before {
      border-radius: 8px;
    }

    /*** hide footer ***/
    ul.pf-c-list.pf-m-inline {
      display: none !important;
    }

    .pf-c-toolbar {
      border-radius: 8px 8px 0px 0px;
    }

    .pf-c-pagination.pf-m-bottom {
      border-radius: 0px 0px 8px 8px;
    }

    .pf-c-sidebar__content {
      background-color: rgba(255, 255, 255, 0) !important;
    }

    .pf-c-card {
      border-radius: 8px;
    }
