---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: authentik
      version: 2024.8.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: authentik-secrets

    authentik:
      secret_key: "" # should be pulled from env
      error_reporting:
        enabled: true
      email:
        host: "mail.hyde.services"
        port: 587
        username: "no-reply@hyde.services"
        use_tls: true
        use_ssl: false
        timeout: 30
        from: "no-reply@hyde.services"

    server:
      ingress:
        enabled: true
        ingressClassName: external-nginx
        hosts:
          - host: auth.hyde.services
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - auth.hyde.services
            secretName: wildcard.hyde.services

    postgresql:
      enabled: true
      auth:
        existingSecret: "authentik-secrets"
        secretKeys:
          userPasswordKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
      primary:
        persistence:
          size: 256Mi

    redis:
      enabled: true
