apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: authentik
            version: 2024.8.3
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: flux-system
    values:
        authentik:
            secret_key: ENC[AES256_GCM,data:B5hUuUQKFL3zUwD69NLL+p6IVEYaweNmh4XakTwRgTUxmkocVaGIaGFbzL8w3qxvtgk=,iv:OIlXI8Tjuv5GXGRnMjg/jjZMs3eoSALSsi0StW1XLGE=,tag:xTgE/SnFnrx/yZyQ4WU3LQ==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:BoopI8eH+JItscXXbkY=,iv:Zf2IB/DfPcFl/61WNQt0+A0BIU1Oz4GmXWMhCLtxDu4=,tag:V/1wvCsdS9+PwTFOxjks8Q==,type:str]
            email:
                host: mail.hyde.services
                port: "587"
                username: no-reply@hyde.services
                password: ENC[AES256_GCM,data:d3rNh+xHFeBmGrPY3PCG4Q==,iv:Ia6h8IMDbMSuLkmDFaw9Be8KsCkw6JNsmuY/8I0Pv2M=,tag:Rgegk8kGRcAipywViP+moA==,type:str]
                use_tls: true
                timeout: "30"
                from: no-reply@hyde.services
        server:
            ingress:
                enabled: true
                ingressClassName: external-nginx
                hosts:
                    - auth.hyde.services
                tls:
                    - secretName: wildcard.hyde.services
                      hosts:
                        - auth.hyde.services
            podAnnotations:
                backup.velero.io/backup-volumes: media
            volumes:
                - name: media
                  persistentVolumeClaim:
                    claimName: authentik-media-pvc
                - name: custom-css
                  configMap:
                    name: authentik-custom-css
            volumeMounts:
                - name: media
                  mountPath: /media
                - name: custom-css
                  mountPath: /web/dist/custom.css
                  subPath: custom.css
        serviceAccount:
            serviceAccountSecret:
                enabled: true
            fullnameOverride: authentik-sa
        postgresql:
            enabled: true
            auth:
                password: ENC[AES256_GCM,data:2q0Dv2FwmWYRSUWRagI=,iv:WZOiSkCxTp35U3ve55EYCznUhMskB6TYI/NXqswQAR8=,tag:QhGDzoMSx33Igm0hSdhLXg==,type:str]
            primary:
                persistence:
                    size: 256Mi
                podAnnotations:
                    backup.velero.io/backup-volumes: data
        redis:
            enabled: true
            master:
                persistence:
                    size: 128Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TVBkZkluQ01lNU5Jd3ds
            TE4zNklJVll5YVFHeGVpN29MMUdXL29CckNjCm9qS3J0WUtkK21LZW9lYSt0K21X
            ZzdwQXIwVzVHMnFqMXdnbmp2UlVXVFEKLS0tIFV0eDdTMXl5WEhWcTd5aW4wdGpw
            aDVxSUFNOUY0SWYybE5iK1JSYk95MEUKHOpUIKJJsU09xb5S5QzqEz720GSiLuBw
            jSMQUpn1Kf1nQg87HdSi0ATj3U6fkzkaemCY+yek1OKdKhlAE8KLMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T11:04:48Z"
    mac: ENC[AES256_GCM,data:u12+tM1L1aFXlC18sRm6Lffxmt+188qDpI/+075pdK9zCZDdci/EI4rUs6xsMuF+cTPJx38DZaKNmVWEqiK/JJS/Ov+yNbmhgqltTkARvfhKGQOexSY/uoASOkekflquS1FJ35O/ER6Zm0TPOiiqPxrLzi7LQV7HJIl+qaJXv+g=,iv:2RcOHwPjjtm005aQDLIp3P9iNhmoLaVlPY/o1OEkhHY=,tag:CtdVlTvnc8/yXIJqXda60w==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret_key|)$
    version: 3.9.0
