apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: authentik-server
    namespace: authentik
    annotations:
        gethomepage.dev/enabled: ENC[AES256_GCM,data:25VhZg==,iv:91Bv4sJDfiLeNhBBNjts8mFqO9pORCbMg/03FIbKNQM=,tag:a3EhN4sxiEZqFyBwV5DHaA==,type:str]
        gethomepage.dev/description: ENC[AES256_GCM,data:h8MhLoA8UOW88C12LCI0Hmkej5qRDhQOjv4dFpAyYolXNoC6RWfCs1iN2w3YeMU=,iv:kA9nYKGpLifuLi/aU8YxnYzv+OVUM+Nu/sCYZc72ymI=,tag:cbCwCtlSJc9ExiNDu0TFKQ==,type:str]
        gethomepage.dev/group: ENC[AES256_GCM,data:c5yOFd7scnM/kHJWrEs=,iv:+L6j2DY/bBLvNBLD1f11qC+2Mj+aRlRaTQDiE79o7+E=,tag:JyqWNu4BPvWtU6eFIe9xwg==,type:str]
        gethomepage.dev/icon: ENC[AES256_GCM,data:M2NGRpIlE0/m,iv:flAr1tWp+aWJMznC4GuKs5ktSW3DmUokpUnsrt9M00o=,tag:drqQFZFUAMSPwNfD0uvy0A==,type:str]
        gethomepage.dev/name: ENC[AES256_GCM,data:mNUO+hiUKYhS,iv:PjZ1UUwNGemqHXiMIxpgwpNBjxKuMJ0U0Ewcoeb6kpQ=,tag:b0Kd1r98isHcjvHwLobQuA==,type:str]
        gethomepage.dev/namespace: ENC[AES256_GCM,data:N+LEdX8hhbpG,iv:t3FzZb1PRmno3Q0vn5hNS8hOOK4EP6rw8oooDzuzN0w=,tag:B2mBdgrK9B4cjhszzR4rWQ==,type:str]
        gethomepage.dev/app: ENC[AES256_GCM,data:zyJtUAjz2mYr,iv:tqRPFF1e+YNxakPQ5qOMYeg5iShg6VRUDJ/VlKfpl38=,tag:z6Dc4suPm1lFWhrzVpNcgQ==,type:str]
        gethomepage.dev/widget.type: ENC[AES256_GCM,data:3ti9Y5a5Wie/,iv:MR2f5GxYj5eoxCDTMTnnyIgdkTTI+vhRiasS4H2j2VU=,tag:1E4RuARG0FpTTBbee25ZOg==,type:str]
        gethomepage.dev/widget.url: ENC[AES256_GCM,data:OqIzjQDlQTrwOO/2R+EH83sURz+YJk3e4OQ=,iv:Ohx+/21Q5B2AlIrfq94xjGEjBn30CrjqN/U1mFlW/BQ=,tag:Q5SXBNxS4TiRd7+QBPIfOg==,type:str]
        gethomepage.dev/widget.key: ENC[AES256_GCM,data:E4Hg+WxFRKjVn+2C0MnJ8yaDzWVwWcbwoucpmgP7f/oHQYAvcRQACZp9K0/RzK3987vqP7b5B1CFSwUM,iv:IHXEf0d+QxBKF61yLlapWauRx/Kgfat2VvdoLmr91E4=,tag:8twi+2+HpZ/tUcGD1k12PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGR2eW5xWjJqUWg5aXN0
            bnZUY25jWnNUeTRDb3Y0VE1Zbk5zK2RPRFFVCnZsYTg1djNaQk9FQmRWN2JHNzE1
            S0NQOEJPQUdIUUJLeUVXbHRyaHB6Y3cKLS0tIEFQN0gwZFQ4b0xNVStVSDhKU0Zo
            Mmg3aDRwZW54a1ZyZytmUFhjUEtDNHMKGZxZ//O4puSOs/H5pwK8eFsLCL69YrJK
            p9xrjiTjXUFC+pzE5YFsXgeOslTFnieufL5sZztaKssKFyMduH0t+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T09:23:13Z"
    mac: ENC[AES256_GCM,data:muO2hZtwsnaD+fXDtwaltx8wI8t4Cy+e+5UsVL37+JHyhBulFsuVf282tuf6xPaAV+IA0ux5g9Lmm/TGXFgDLQ25kNw6TPfPPEVZc6GLrr0G6ARoJ74qu4qKfgQ1qJkrfW2EdD6+N4ZX+z1oeRDHkGbqjkJBkjAfGnYnyzh+Heo=,iv:BVPQZkP6UzHw/qD2pgpF3ngZ0Gp8ZpjbCwfEaMBvzuY=,tag:9gIGGt2JZ/6UPJZD+CfrDw==,type:str]
    pgp: []
    encrypted_regex: ^(rules|annotations|)$
    version: 3.9.1
