---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: unifi-protect-backup
    namespace: unifi-protect-backup
spec:
    interval: 5m
    install:
        createNamespace: true
    chart:
        spec:
            chart: ./Helm/apps/unifi-protect-backup
            reconcileStrategy: Revision
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system
    values:
        unifi-protect-backup:
            replicas: 1
