---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: homarr
      version: 1.2.6
      sourceRef:
        kind: HelmRepository
        name: oben01
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/ajnart/homarr
      tag: 0.14.6
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hosts:
        - host: homarr.k3s.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - homarr.k3s.hyde.services
          secretName: wildcard.hyde.services
    persistence:
      size: 128Mi
