---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace.yaml
  - limit-egress.yaml
  - ghcr-secret.sops.yaml
  - secret-super-sops.yaml
  - secret.sops.yaml