apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-plex
  namespace: media-servers
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  policyTypes:
    - Egress
  egress:
    # Allow DNS egress
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow DNS everywhere
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow egress to HTTP and HTTPS everywhere
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow HTTP/HTTPS egress everywhere
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
