apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: plex-claim-secret
    namespace: media-servers
data:
    PLEX_CLAIM: ENC[AES256_GCM,data:1YXwzNsQtFEhlCGkMHx/L/Km10r2HPNk3jG5rFGIVZoKufNk,iv:HV+HoY/ad7ZUmPmhIbF4I4QDKd+t1Km1PydR00/OuiM=,tag:sF3bjDPMYJar90nifwVgDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYmg3UHJOeWRHRDhaUUFL
            QWFycHFNSHJuWjhsZjU2aUhWcEpmWDdFNzFVClFLOUk5d0RQR3dRMGdwOWN5TWxp
            MzFEaFIxQmZZNG1nT0FxOEpaTkN1c28KLS0tIEhyUTFRay9zUUZvRFFEaWtYZS9N
            NlFlbzBpTEJ6MEYzSFd4cDNqYnM1Y1kKU2bP3n/hczkdvK+TRILSkbItf3hdA+tX
            luJuHRfpxobLDAgoLSAEMb2t5s6AaRFgkossqk+YLmAdFIqNdT2dhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T11:29:50Z"
    mac: ENC[AES256_GCM,data:BR+PUyqhnUuBTDLmQnHxJNuAx8LLuwlevq8RU0759u70g3MC75MIowNgmYjWtdd3RAc47KMezVQ3DHIVT2SNEcQWaBYle5xI+f4rhV/KgruXFKDPo4Zv0iTwr6WZtoqfPSQwpUCf3R9L/urEtUaZXrpDRWYBWchSjsmNUWdRNCc=,iv:5tFNw7u6igPCcu4JOzEGXi28ZvHACs/+7kFp89s8vig=,tag:NyL91ao6IhdN3QWVJykgAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.0
