---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: aars
    namespace: aars
spec:
    interval: 5m
    install:
        createNamespace: true
    chart:
        spec:
            chart: ./Helm/apps/aars
            reconcileStrategy: Revision
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system

