apiVersion: v1
data:
    cloud: ENC[AES256_GCM,data:SqArRn3oTVU3jluwDsEnZxbmZ678zOmpFolfDLioyNEWrsQsJg4urCZxzCiL2sn32q6IggwA/mgZiDym2C5MZiIipOCCWQ8XmPv8vseFO6y3PfTfXnqEIqJbba2UWnX+XhgNsuRukhe6lh0ee10S7wvkwwjsNoDZAFpC0lSfky6mndhQy4ALlOd8xxHCutQvW556IpLs0+22f1atQQ==,iv:hgfSXkVfY+dXqq2fs5Vv0CjIm5CdIxb9W76HGiRe+IY=,tag:emeB1swDLd9rD3Uw6d1ycg==,type:str]
kind: Secret
metadata:
    name: cloud-credentials-minio
    namespace: velero
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T07:13:39Z"
    mac: ENC[AES256_GCM,data:qHquohYjL0rr55i7TJHpF8Z/Zr+E0uvpeAfnltTCx6UMK88cs4569L/hGMnhoMfF1bK+C0KEBy9flhk0tM9ReAti+h8L+mLz+vbgEg69GiDmFAyD+QNQk4lMOT0A+5HrOoF2htpusfmg5XyByIOeKpcKTgZAIOhu7C58L1eO/Ys=,iv:9dfalneTTXjanZ1/ijdzbR3OD7ME0/XXfEeGZNwzP30=,tag:6C5OzZOn4XBgKBs2mI7ZRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.0
---
apiVersion: v1
data:
    repository-password: ENC[AES256_GCM,data:P7/hghTS3CFP/akK9a8z7a9MmG0aTBbEpVqwHs/UcqTYj2lVfps56Bnyd4WY,iv:pe5vjGGqkWrdZAjOu1jZAwasGZAvs6ZdUxCJWGqHlq4=,tag:akqTRjBKWPQkKZ7jUQzooA==,type:str]
kind: Secret
metadata:
    name: velero-repo-credentials
    namespace: velero
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T07:13:39Z"
    mac: ENC[AES256_GCM,data:qHquohYjL0rr55i7TJHpF8Z/Zr+E0uvpeAfnltTCx6UMK88cs4569L/hGMnhoMfF1bK+C0KEBy9flhk0tM9ReAti+h8L+mLz+vbgEg69GiDmFAyD+QNQk4lMOT0A+5HrOoF2htpusfmg5XyByIOeKpcKTgZAIOhu7C58L1eO/Ys=,iv:9dfalneTTXjanZ1/ijdzbR3OD7ME0/XXfEeGZNwzP30=,tag:6C5OzZOn4XBgKBs2mI7ZRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.0
