apiVersion: v1
data:
    cloud: ENC[AES256_GCM,data:HI2x9insMf2MqdivHsJjzWL6qreYJ973Y6L4msMHGmXOtzrUpQnMrzNZzeRHDF+gx3wXawBxIs5koIr+9KGn/lQbJfaCsw4UQkDPi6cRTJf4iGrHft1gsLSGyx42BINUeE1Ohjkj1Jax2sqtaDVC6W849OuvQtUzVRPnZaKpaMx4DIpNOSaT3eFzuv7g66neUu1G9YtJ20ArA4us6g==,iv:EC4xPlJtafSOuaScKgCuqcOF8Z482pMd7W97HPEL31A=,tag:eaKgn8PchJcEFFbqkdF6ng==,type:str]
kind: Secret
metadata:
    name: cloud-credentials-minio
    namespace: velero
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T04:26:33Z"
    mac: ENC[AES256_GCM,data:v1tt3bdC3fD3L0NXp/P2qq+qexdS3xEhYlnT0Wi8blmieAWBa6elIt/otRuGFpncIGnbIdf6Sew9CwCKPXUiE/tolawdQxK/WVMwG7+vrSYPWvpN5X5a1/VdK9t8DItNO5V+6PkVqLTmbdtJvnokW3vBELLxdheCmCRV94xMUbc=,iv:xCOdwrNxvL59M8tl+ok6u8HlolnHGb7ZfVu8ImMQVV0=,tag:DubOqocqHuLcfJ3mnHkW8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.1
---
apiVersion: v1
data:
    repository-password: ENC[AES256_GCM,data:P7/hghTS3CFP/akK9a8z7a9MmG0aTBbEpVqwHs/UcqTYj2lVfps56Bnyd4WY,iv:pe5vjGGqkWrdZAjOu1jZAwasGZAvs6ZdUxCJWGqHlq4=,tag:akqTRjBKWPQkKZ7jUQzooA==,type:str]
kind: Secret
metadata:
    name: velero-repo-credentials
    namespace: velero
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T04:26:33Z"
    mac: ENC[AES256_GCM,data:v1tt3bdC3fD3L0NXp/P2qq+qexdS3xEhYlnT0Wi8blmieAWBa6elIt/otRuGFpncIGnbIdf6Sew9CwCKPXUiE/tolawdQxK/WVMwG7+vrSYPWvpN5X5a1/VdK9t8DItNO5V+6PkVqLTmbdtJvnokW3vBELLxdheCmCRV94xMUbc=,iv:xCOdwrNxvL59M8tl+ok6u8HlolnHGb7ZfVu8ImMQVV0=,tag:DubOqocqHuLcfJ3mnHkW8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.9.1
