apiVersion: velero.io/v1
kind: Schedule
metadata:
    name: general
    namespace: velero
spec:
    schedule: '00 07 * * *'
    template:
        hooks: {}
        includedNamespaces:
          - media
          - portainer
        snapshotVolumes: true
        ttl: 2190h0m0s
    useOwnerReferencesInBackup: false