apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: k8s-homelab
  namespace: velero
spec:
  schedule: "0 1 * * *"
  template:
    hooks: {}
    includedNamespaces:
      - authentik
      - changedetection
      - database
      - jenkins
      - knick-knacks
      - mailserver
      - media-downloaders
      - media-managers
      - media-servers
      - monitoring
      - nextcloud
      - paperless-ngx
      - portainer
      - wordpress
    volumeSnapshotLocations:
      - k8s-homelab
    snapshotVolumes: true
    ttl: 168h0m0s # 7 days
  useOwnerReferencesInBackup: false
