---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: qbittorrent.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: qbittorrent
                port:
                  number: {{ .Values.qbittorrent.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: sabnzbd.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: plex
                port:
                  number: {{ .Values.sabnzbd.port }}
