---
{{- with .Values.qbitorrent }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitorrent
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: qbitorrent
    app.kubernetes.io/name: qbitorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: qbitorrent
      app.kubernetes.io/name: qbitorrent
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: appdata
      labels:
        app.kubernetes.io/instance: qbitorrent
        app.kubernetes.io/name: qbitorrent
    spec:
{{- if .nodeSelector }}
      nodeSelector:
        {{ toYaml .nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: qbitorrent
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1001"
            - name: GUID
              value: "1001"
{{- if .resources }}
          resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
          ports:
            - name: web
              containerPort: {{ .port }}
          volumeMounts:
            - name: appdata
              mountPath: /config
            - name: nfs-media-data
              mountPath: /data
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .port }}
      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: qbitorrent-appdata-pvc
        - name: nfs-media-data
          nfs:
            path: "/mnt/Slow/Media"
            server: "10.0.3.7"
---

apiVersion: v1
kind: Service
metadata:
  name: qbitorrent
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: qbitorrent
    app.kubernetes.io/name: qbitorrent
  ports:
    - name: qbitorrent
      protocol: TCP
      port: {{ .port }}

{{- end }}
