---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.qbittorrent.appdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-appdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.sabnzbd.appdata }}