---
{{- with .Values.unpackerr }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: unpackerr
    app.kubernetes.io/name: unpackerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: unpackerr
      app.kubernetes.io/name: unpackerr
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: unpackerr
        app.kubernetes.io/name: unpackerr
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      nodeSelector:
{{ toYaml .nodeSelector | indent 8 }}
      containers:
        - name: unpackerr
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: TZ
              value: "Australia/Melbourne"
          resources:
{{ toYaml .resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config/unpackerr.conf
              subPath: unpackerr.conf
            - name: nfs-media-data
              mountPath: /data

      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: unpackerr-config
        - name: nfs-media-data
          nfs:
            path: "/mnt/Slow/Media"
            server: "10.0.3.7"
{{- end }}
