---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.k3s.hyde.services"
      secretName: ingress
  rules:
    - host: paperless.k3s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: paperless
                port:
                  number: {{ .Values.paperlessngx.port }}