---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailu
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mailu
      version: 2.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: mailu
        namespace: flux-system
  values:
    domain: hyde.services
    hostnames:
      - mail.hyde.services
    initialAccount:
      domain: hyde.services
      username: alex
      password:
        existingSecret: mailu-secrets
      existingSecretPasswordKey: password
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: mailu.k3s.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - mailu.k3s.hyde.services
          secretName: wildcard.hyde.services
    logLevel: INFO
    timezone: Australia/Melbourne
    limits:
      authRatelimit:
        ip: 100/minute;3600/hour
        user: 100/day
      messageSizeLimitInMegabytes: 200
    persistence:
      size: 1Gi
    secretKey:
      existingSecret: mailu-secrets
