apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailu
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mailu
      version: 2.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: mailu
        namespace: flux-system
  values:
    domain: hyde.services
    hostnames:
      - mail.hyde.services
    initialAccount:
      mode: ifmissing
    ingress:
      enabled: true
      ingressClassName: nginx
      existingSecret: wildcard.hyde.services
    logLevel: INFO
    subnet: 172.16.0.0/16
    timezone: Australia/Melbourne
    limits:
      authRatelimit:
        ip: 100/minute;3600/hour
        user: 100/day
      messageSizeLimitInMegabytes: 200
    persistence:
      size: 1Gi
    secretKey:
      existingSecret: mailu-secrets
    front:
      hostPort:
        enabled: false
      externalService:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
    tika:
      enabled: false
    oletools:
      enabled: false
    clamav:
      enabled: false
    rspamd:
      enabled: true
    webmail:
      enabled: true
    redis:
      enabled: true
      master:
        enabled: true
        persistence:
          enabled: true
          size: 128Mi
