---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailu
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mailu
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: flux-system
      interval: 5m
  values:
    domain: hyde.services
    hostnames:
      - mail.hyde.services
    initialAccount:
      domain: hyde.services
      username: alex
      password:
        existingSecret: mailu-secrets
      existingSecretPasswordKey: password
    logLevel: INFO
    timezone: Australia/Melbourne
    limits:
      authRatelimit:
        ip: 100/minute;3600/hour
        user: 100/day
      messageSizeLimitInMegabytes: 200
    persistence:
      size: 1Gi
    secretKey:
      existingSecret: mailu-secrets
